# Required metadata
sonar.jdbc.url=jdbc:postgresql://localhost/sonar 
sonar.host.url=http://localhost:9000
sonar.projectKey=roart:aether
sonar.projectName=Aether Disk Search Engine
sonar.projectVersion=0.10-SNAPSHOT

# Comma-separated paths to directories with sources (required)
sonar.sources=.
sonar.java.binaries=.

# Language
#sonar.language=java

# Encoding of the source files
#sonar.sourceEncoding=UTF-8

sonar.coverage.jacoco.xmlReportPaths=jacoco/target/site/jacoco-aggregate/jacoco.xml
<sonar.jacoco.reportPath>${project.basedir}/../target/jacoco.exec</sonar.jacoco.reportPath>