<project>
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>roart</groupId>
    <artifactId>aether-common-communication-message</artifactId>
    <relativePath>../pom.xml</relativePath>
    <version>0.10-SNAPSHOT</version>
  </parent>
  <groupId>roart</groupId>
  <artifactId>aether-common-communication-message-kafka</artifactId>
  <packaging>jar</packaging>
  <version>0.10-SNAPSHOT</version>
  <name>Aether Common Communication Message Kafka</name>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <!-- avoid putting test dependencies on the module path which causes resolution failures -->
          <useModulePath>false</useModulePath>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-logging</artifactId>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-constants</artifactId>
      <version>${aether.version}</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-model</artifactId>
      <version>${aether.version}</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-communication-message-model</artifactId>
      <version>${aether.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.kafka</groupId>
      <artifactId>kafka-clients</artifactId>
      <version>${kafka.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.kafka</groupId>
      <artifactId>kafka-streams</artifactId>
      <version>${kafka.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-math3</artifactId>
      <version>${commons.math3.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>${commons.lang3.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>${guava.version}</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>${jackson.annotations.version}</version>
    </dependency>
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
      <version>1.15</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.kafka</groupId>
      <artifactId>spring-kafka-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.kafka</groupId>
      <artifactId>spring-kafka</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
