<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>roart</groupId>
    <artifactId>aether</artifactId>
    <relativePath>../pom.xml</relativePath>
    <version>0.10-SNAPSHOT</version>
  </parent>
  <groupId>roart</groupId>
  <artifactId>aether-jacoco</artifactId>
  <version>0.10-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Aether Disk Search Engine Jacoco</name>
  <build>
    <plugins>
      <!-- JaCoCo plugin to prepare agent in modules and create an aggregate report at the root -->
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>${jacoco.version}</version>
        <executions>
          <!-- Generate an aggregated report at the reactor root during verify -->
          <execution>
            <id>report-aggregate</id>
            <phase>verify</phase>
            <goals>
              <goal>report-aggregate</goal>
            </goals>
            <configuration>
                <dataFileIncludes>
                    <dataFileInclude>**/jacoco.exec</dataFileInclude>
                </dataFileIncludes>
              <outputDirectory>${project.reporting.outputDirectory}/jacoco-aggregate</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-collections</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-communication-factory</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-communication-integration-camel</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-communication-integration-model</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-communication-integration-spring</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-communication-message-kafka</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-communication-message-model</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-communication-message-pulsar</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-communication-model</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-communication-rest</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-config</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-constants</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-convert</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-database</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-eureka</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-filesystem</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-inmemory-factory</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-inmemory-hazelcast</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-inmemory-model</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-inmemory-redis</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-inmemory-message</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-machinelearning</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-model</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-searchengine</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-service</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-synchronization</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-util</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-webflux</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-zookeeper</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-leader</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-queue</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-common-hcutil</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-calibre</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-convert-controller</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-djvutxt</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-pdftotext</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-tika</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-wvtext</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-core</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-cassandra</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-database-controller</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <!--dependency>
      <groupId>roart</groupId>
      <artifactId>aether-datanucleus</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency-->
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-dynamodb</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-hbase</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-hibernate</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-springdata</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-database-test</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-filesystem-controller</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-hdfs</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-local</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-s3</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-swift</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-filesystem-test</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-machinelearning-controller</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <!--dependency>
      <groupId>roart</groupId>
      <artifactId>aether-mahout-mr</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency-->
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-mahout-spark</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-opennlp</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-spark-ml</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-searchengine-controller</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-elastic</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-lucene</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-solr</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-searchengine-test</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-servicemanager-docker</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-servicemanager-mesos</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <!--dependency>
      <groupId>roart</groupId>
      <artifactId>aether-servicemanager-openshift</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency-->
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-servicemanager-simple</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether.shadow.elastic</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether.shadow.fabric8</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether.shadow.hbase</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether.shadow.mahout.mr</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether.shadow.mahout.spark</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether.shadow.mahout.sparkcore</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether.shadow.s3</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether.shadow.spark</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether.shadow.zookeeper</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>roart</groupId>
      <artifactId>aether-testdata</artifactId>
      <version>0.10-SNAPSHOT</version>
    </dependency>
  </dependencies>
</project>
